name: Fetch Price Dev
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
    branches:
      - dev
      - price

concurrency: 'dev'

jobs:
  health-check:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-22.04
    name: Fetch Price Rate
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.GH_AUTOMATION_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          yarn install 

      - name: Run scripts
        run: |
          NODE_ENV=development yarn fetch-price

      - name: Commit changes
        id: commit_changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Github-Bot
          author_email: scheduler@github.io
          message: '[CI Skip] Fetch Price (dev)'

      - name: Log commit changes
        run: |
          echo "pushed: ${{ steps.commit_changes.outputs.pushed }}"

      - name: Deploy Assets to Cloudflare Pages
        if: steps.commit_changes.outputs.pushed == 'true'
        id: cloudflare_deployment
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'sw-static-cache'
          gitHubToken: ${{ secrets.GH_AUTOMATION_TOKEN }}
          branch: dev
          directory: './data'
          wranglerVersion: '3'